### ISSUE TITLE
Line placement bug

### ISSUE THREAD

**Issue by smacinnes** [moovel/lab-opendatacam#48]
When viewing the tracker on different screen sizes, the lines appear in different places. It seems that this is purely visual and does not affect the counting itself. Just thought I'd report it in case you guys weren't aware. 

From my phone (where I set it up):
![opendatacammobile](https://user-images.githubusercontent.com/40182280/44269821-090db280-a20c-11e8-9d30-85d78e5dc696.jpg)

From my desktop:
![opendatacamdesktop](https://user-images.githubusercontent.com/40182280/44269721-cba92500-a20b-11e8-802c-f13c8b402fdc.PNG)

**Comment by tdurand** [comment]
Hey, thanks for you comment, we are currently working on an update that will improve the responsiveness of the UI.

**Comment by tdurand** [comment]
fixed on branch 0.2 : https://github.com/moovel/lab-opendatacam/commit/ba2768b792600e66005d43d9fe3d3576cc3a5c97
