### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by b-g** [moovel/lab-opendatacam#50]
- [x] polish icons @mmmmmmmmmmmmmmmm 
- [x] introduce changelog @tdurand 
- [x] bump version in package.json shortly before release 
- [x] create release on github : https://github.com/moovel/lab-opendatacam/releases

**Comment by b-g** [comment]
@tdurand It seems we forgot to do v0.1 release ... could you tag the latest commit before the path mode was introduced with v0.1?

**Comment by tdurand** [comment]
Done @b-g , I've wrote the changelog directly on the release page: https://github.com/moovel/lab-opendatacam/releases

**Comment by b-g** [comment]
@tdurand Thanks!!

**Comment by tdurand** [comment]
Ok, saw that @mmmmmmmmmmmmmmmm had pushed the new icons, the path thing was already working properly. Can close, the latest release is v0.2.2, published here: https://github.com/moovel/lab-opendatacam/releases/tag/v0.2.2
