### ISSUE TITLE
Improve Jetson Flashing documentation

### ISSUE THREAD

**Issue by yannikw93** [moovel/lab-opendatacam#53]
1) Maybe you could provide a small help for everyone who is new to Ubuntu. Something like first steps or prerequisites.

This could be
> Host PC with Ubuntu is needed
> Which version of Ubuntu is needed (16.04 I think) and how to install (https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop-1604#4)
> How to connect the Jetson with Host PC

2) I found this tutorial to be very helpful with getting started and especially with flashing the Jetson so maybe you can incorporate it?

https://www.youtube.com/watch?v=D7lkth34rgM

3) Last but not least I think it would help everyone who is not used to Ubuntu if you could put the Notice with the automatic installation at the very top of the page. Right after the flashing part. I realized that the code is not suitable for just copy and paste to the terminal on the Jetson (like changing directories back to install new files for example).

**Comment by paddygoat** [comment]
Flashing to Jetson ..... That video makes it look easy, too easy. It's not a complete tutorial by any means as many important details / problems are skipped for convenience.

**Comment by florianporada** [comment]
Hi @paddygoat, what would you suggest as a solution for that problem? 

@yannikw93: I updated the Readme file. The install-script part is still on the lower part though.. since it needs some more testing.

**Comment by paddygoat** [comment]
Somebody, preferably someone not connected to Nvidia, should show all the Jetpack flashing pitfalls. I think I encountered quite a few: eg

- Host computer not compatible even though on same Ubuntu version - OS had to be freshly installed.

- IP addresses are slightly different for host and Jetson.

- WFI and Bluetooth internet ports are hard to identify.

- Internet to USB 'switching' should be tested before trying to flash.

- USB port is difficult to identify and to make a connection.

- The Jetson flashing menu has 'hidden' sub menus that are difficult to find

- The flash has to be done in two stages (for me anyway) - the OS flashed first but NOT selected for 2nd flash.

- Etc etc etc.

**Comment by tdurand** [comment]
Renamed as "Improve jetson flashing documentation" , maybe we can add extra some guidance and common problems section in our README but the nvidia docs are pretty good once you understand you need another ubuntu machine to flash the jetson.

**Comment by paddygoat** [comment]
I would have to disagree with that. The Nvidia documentation is confusing.  It seems to imply that you can perform the second stage of the flashing with the USB cable with the IP address of the USB port of the Jackson. 
 In my experience, the second half of the flash process is only reliably performed with Evernet cable. Not USB cable. 
My Internet set up has no Router ,  just Wi-Fi and Bluetooth. Maybe the flashing process works absolutely fine if you have a Rueter I don't know. If somebody has no Rueter then  to perform the second half of the flash they need  Evernet cable and IP address of the Jackson, which keeps changing!  
Apologies for bad spelling, its  Voice to text program.

**Comment by tdurand** [comment]
I found this tutorial that will help a bit on the flashing part, adding it to the README: https://tm3.ghost.io/2018/07/06/setting-up-the-nvidia-jetson-tx2/
