### ISSUE TITLE
Mapping of Yolo classes to OpenMojis

### ISSUE THREAD

**Issue by b-g** [moovel/lab-opendatacam#68]
Hi @tdurand @mmmmmmmmmmmmmmmm!

Here are all OpenMojis which are currently available: 
[openmoji-black-svg.zip](https://github.com/moovel/lab-opendatacam/files/2992598/openmoji-black-svg.zip)

I think I would just vote to simply add the mapping of yolo classes to icons to the config file and copy the emoji to an assets folder.

```js
{
	"PATH_TO_YOLO_DARKNET": "/darknet",
	"VALID_CLASSES": ["*"],
	"DISPLAY_CLASSES": ["bicycle", "car", "bus", "motorbike", "truck", "person"]
  	"DISPLAY_CLASSES_ICONS": ["1F6B2.svg", "1F697.svg", "1F68C.svg", "1F3CD.svg", "1F69B.svg", "1F468.svg"]
}
```

or

```json
{
	"PATH_TO_YOLO_DARKNET": "/darknet",
	"VALID_CLASSES": ["*"],
	"DISPLAY_CLASSES": [
	  { "class": "bicycle", "icon": "1F6B2.svg"},
	  ...
	]
}
```
Both fine for me.

**Comment by tdurand** [comment]
Great thanks + agree with config 👍 .

**Comment by tdurand** [comment]
Do we have also a openmoji-white for the dark / light variation ?

Or maybe I could hack this by styling the color on runtime with currentColor: https://css-tricks.com/cascading-svg-fill-color/  and inlining the svgs in the code: https://github.com/gilbarbara/react-inlinesvg

**Comment by tdurand** [comment]
ok done, documented here: https://github.com/moovel/lab-opendatacam/blob/v2/doc/CONFIG.md#display-custom-classes
