### ISSUE TITLE
node.js and darknet-net binding not working

### ISSUE THREAD

**Issue by artynet** [moovel/lab-opendatacam#72]
please guys take a look at my issue here :

https://github.com/meso-unimpressed/darknet-net/issues/8

basically the command string is not working because the darknet executable crashes. In addition to this,  it seem that when building for processing the video file (and then running the build), the webcam server is started anyway. Please give me some pointers about it...

Best, Arturo

**Comment by tdurand** [comment]
seems this issue was answered on the meso-unimpressed repo.

BTW we are working on Opendatacam v2 which will use a different implementation of darknet.
