### ISSUE TITLE
Json store in cloud directly

### ISSUE THREAD

**Issue by shams3049** [moovel/lab-opendatacam#83]
Has anyone tried to store Json data generated by the application directly to google or any other cloud. 

I am missing the understanding of how the it works systematically: meaning how to approach the problem. 

I want to implement this in the end: https://cloud.google.com/storage/docs/json_api/

**Comment by tdurand** [comment]
For this you would need either to:

- To write some app that consumes the APIs endpoint and post them to your cloud provider
- Fork and rewrite the persistent layer to persist directly to another cloud provider: https://github.com/moovel/lab-opendatacam/blob/v2/server/db/DBManager.js
- Change the mongodb adress of persistence so you persist on some mongodb cloud provider directly: https://github.com/moovel/lab-opendatacam/blob/v2/server/db/DBManager.js#L8

I will document the latest option
